<a href="https://colab.research.google.com/github/balanmaria/Python_for_Programmers/blob/main/22_04_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
numbers = np.array([2, 3, 5, 7, 11])
numbers

array([ 2,  3,  5,  7, 11])

In [2]:
type(numbers)

numpy.ndarray

In [3]:
np.array([[1,2,3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
integers = np.array([[1,2,3], [4, 5, 6]])
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])
floats


array([0. , 0.1, 0.2, 0.3, 0.4])

In [6]:
integers.dtype

dtype('int64')

In [7]:
floats.dtype

dtype('float64')

In [8]:
integers.ndim

2

In [9]:
floats.ndim

1

In [10]:
integers.shape

(2, 3)

In [11]:
floats.shape

(5,)

In [12]:
integers.size

6

In [13]:
integers.itemsize

8

In [14]:
floats.size

5

In [15]:
floats.itemsize

8

In [16]:
for row in integers:
  for column in row:
    print(column, end = ' ')
  print()

1 2 3 
4 5 6 


In [17]:
for i in integers.flat:
  print(i, end = ' ')

1 2 3 4 5 6 